### ISSUE TITLE
pytest failing with torch (cuda) backend

### ISSUE THREAD

**Issue by Shiva-sankaran** [keras-team/keras-cv#2268]
Hi,

I have been trying to set up the working environment following this [doc](https://github.com/keras-team/keras-cv/blob/6a0ef4443206e7084ba43cfc856e5a8fdd44bb1c/.github/CONTRIBUTING.md#set-up-environment) with torch (cuda) as backend, also I had to upgrade Keras to 3 from 2 as per this [issue](https://github.com/keras-team/keras-cv/issues/2111) . Running pytest after these steps results in multiple failures (118 to be precise). I am not sure if this is expected or if I am missing something because I see simple errors like "TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first." in the test logs. Additional running with Tensorflow backend does not yield any failing tests.

I am able to reproduce this in google [colab](https://colab.research.google.com/drive/1q5nU3UozuNBHTb1B8hJPmCGycETPHJ8R?usp=sharing) as well. Sorry if this is the wrong place to post this, and any input will be highly appreciated.

**Comment by divyashreepathihalli** [comment]
This should be fixed now. Can you check?

**Comment by Shiva-sankaran** [comment]
No, pytest still fails with 117 failing tests (118 previously). I am not sure which one was fixed, but the device error still persists.

**Comment by divyashreepathihalli** [comment]
Fixed!
